using System;
using System.Collections.Generic;
using System.Text;

namespace MHWSaveUtils
{
    public enum EquipmentType : uint
    {
        Armor = 0,
        Weapon = 1,
        Charm = 2,
        Kinsect = 4,
        None = 0xFFFFFFFF,
    }

    public enum ArmorPieceType : uint
    {
        Head = 0,
        Chest = 1,
        Arms = 2,
        Waist = 3,
        Legs = 4,
    }

    public enum WeaponType : uint
    {
        GreatSword = 0,
        SwordAndShield = 1,
        DualBlades = 2,
        LongSword = 3,
        Hammer = 4,
        HuntingHorn = 5,
        Lance = 6,
        Gunlance = 7,
        SwitchAxe = 8,
        ChargeBlade = 9,
        InsectGlaive = 10,
        Bow = 11,
        HeavyBowgun = 12,
        LightBowgun = 13,
    }

    public enum BowGunMod : uint
    {
        RecoilSupressor = 0,
        ReloadAssist = 1,
        DeviationSupressor = 2,
        CloseRangeUp = 3,
        RangedAttackUp = 4,
        Shield = 5,
        None = 0xFFFFFFFF,
    }

    public enum KinsectType : uint
    {
        NoElement = 0,
        Fire = 1,
        Water = 2,
        Ice = 3,
        Thunder = 4,
        Dragon = 5,
        None = 0xFFFFFFFF,
    }

    public enum AugmentationType : uint
    {
        Empty = 0,
        Attack = 1,
        Affinity = 2,
        Defense = 3,
        SlotUpgrade = 4,
        HealthRegen = 5,
        ArmorIsAugmented = 6,
        None = 0xFFFFFFFF,
    }

    public enum Decoration : uint
    {
        AntidoteJewel1 = 0,
        AntiparaJewel1 = 1,
        PepJewel1 = 2,
        SteadfastJewel1 = 3,
        AntiblastJewel1 = 4,
        SutureJewel1 = 5,
        DefLockJewel1 = 6,
        EarplugJewel3 = 7,
        WindResistJewel2 = 8,
        FootingJewel2 = 9,
        AttackJewel1 = 10,
        DefenseJewel1 = 11,
        VitalityJewel1 = 12,
        RecoveryJewel1 = 13,
        FireResJewel1 = 14,
        WaterResJewel1 = 15,
        IceResJewel1 = 16,
        ThunderResJewel1 = 17,
        DragonResJewel1 = 18,
        ResistorJewel1 = 19,
        BlazeJewel1 = 20,
        StreamJewel1 = 21,
        FrostJewel1 = 22,
        BoltJewel1 = 23,
        DragonJewel1 = 24,
        VenomJewel1 = 25,
        ParalyzerJewel1 = 26,
        SleepJewel1 = 27,
        BlastJewel1 = 28,
        PoisoncoatJewel3 = 29,
        ParacoatJewel3 = 30,
        SleepcoatJewel3 = 31,
        BlastcoatJewel3 = 32,
        ReleaseJewel3 = 33,
        ExpertJewel1 = 34,
        CriticalJewel2 = 35,
        TenderizerJewel2 = 36,
        ChargerJewel2 = 37,
        HandicraftJewel3 = 38,
        DrawJewel2 = 39,
        DestroyerJewel2 = 40,
        KOJewel2 = 41,
        DrainJewel1 = 42,
        FlightJewel2 = 43,
        ThrottleJewel2 = 44,
        ChallengerJewel2 = 45,
        FlawlessJewel2 = 46,
        PotentialJewel2 = 47,
        FortitudeJewel1 = 48,
        FurorJewel2 = 49,
        SonorousJewel1 = 50,
        MagazineJewel2 = 51,
        TrueshotJewel1 = 52,
        ArtilleryJewel1 = 53,
        HeavyArtilleryJewel1 = 54,
        SprinterJewel2 = 55,
        PhysiqueJewel2 = 56,
        RefreshJewel2 = 57,
        HungerlessJewel1 = 58,
        EvasionJewel2 = 59,
        JumpingJewel2 = 60,
        IronwallJewel1 = 61,
        SheathJewel1 = 62,
        FriendshipJewel1 = 63,
        EnduringJewel1 = 64,
        SatiatedJewel1 = 65,
        GobblerJewel1 = 66,
        GrinderJewel1 = 67,
        BomberJewel1 = 68,
        FungiformJewel1 = 69,
        ProtectionJewel1 = 70,
        MeowsterJewel1 = 71,
        BotanyJewel1 = 72,
        GeologyJewel1 = 73,
        MightyJewel2 = 74,
        StonethrowerJewel1 = 75,
        TipToeJewel1 = 76,
        BraceJewel3 = 77,
        SmokeJewel1 = 78,
        MirewalkerJewel1 = 79,
        SpecimenJewel1 = 80,
        MiasmaJewel1 = 81,
        ScentJewel1 = 82,
        IntimidatorJewel1 = 83,
        SliderJewel2 = 84,
        MedicineJewel1 = 85,
        ForceshotJewel3 = 86,
        PierceJewel3 = 87,
        SpreadJewel3 = 88,
        EnhancerJewel2 = 89,
        CrisisJewel1 = 90,
        DragonsealJewel3 = 91,
        MaintenanceJewel1 = 92,
        MightyBowJewel2 = 93,
        MindsEyeJewel2 = 94,
        ShieldJewel2 = 95,
        SharpJewel2 = 96,
        ElementlessJewel2 = 97,
        None = 0xFFFFFFFF,
    }
}
